# Generated by Django 4.2.7 on 2024-03-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0022_alter_employee_taxcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeIn', models.DateTimeField(blank=True, null=True)),
                ('TimeOut', models.DateTimeField(blank=True, null=True)),
                ('Late', models.FloatField(blank=True, default=0, null=True)),
                ('WorkHour', models.FloatField(blank=True, default=0, null=True)),
                ('EmpID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
