# Generated by Django 4.2.7 on 2024-04-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkPlan', models.TextField()),
                ('IsComplete', models.BooleanField(default=False)),
                ('Date', models.DateField()),
                ('TimeSheetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timesheet.timesheet')),
            ],
        ),
    ]
