# Generated by Django 4.2.11 on 2024-04-17 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leaverequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='LeaveEndHour',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='LeaveStartHour',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
