# Generated by Django 4.2.11 on 2024-04-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_leaverequest_leaveendhour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='LeaveEndHour',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='LeaveStartHour',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='LeaveEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='LeaveStartDate',
            field=models.DateTimeField(),
        ),
    ]
