# Generated by Django 4.2.7 on 2024-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0013_alter_leavetype_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xuất thông tin nghỉ phép",
                "verbose_name_plural": "Xuất thông tin nghỉ phép",
            },
        ),
    ]
