# Generated by Django 4.2.7 on 2024-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ConfigSchedule',
        ),
        migrations.AddField(
            model_name='configschedule',
            name='Using',
            field=models.BooleanField(default=False),
        ),
    ]
