# Generated by Django 4.2.7 on 2024-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_configschedule_configschedule_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='Color',
            field=models.CharField(default='#ccc', max_length=20),
        ),
    ]
