# Generated by Django 4.2.7 on 2024-03-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='Coefficient',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
            preserve_default=False,
        ),
    ]
