# Generated by Django 4.2.7 on 2024-02-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_type', '0003_leavetype_leavetypedescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='Subsidize',
        ),
    ]
