# Generated by Django 4.2.7 on 2024-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_type", "0004_remove_leavetype_subsidize"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leavetype",
            options={
                "ordering": ["LeaveTypeID"],
                "verbose_name": "Loại nghỉ phép",
                "verbose_name_plural": "Loại nghỉ phép",
            },
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="LeaveTypeDescription",
            field=models.CharField(max_length=1000, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="LeaveTypeID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="LeaveTypeName",
            field=models.CharField(max_length=255, verbose_name="Loại nghỉ phép"),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="LimitedDuration",
            field=models.IntegerField(verbose_name="Số ngày nghỉ tối đa"),
        ),
    ]
