# Generated by Django 4.2.7 on 2024-02-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_employee_empstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PhotoPath',
            field=models.ImageField(default='default.jpg', upload_to='employee_photos/'),
        ),
    ]
