# Generated by Django 4.2.7 on 2024-03-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_bankaccountnumer_employee_bankaccountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='TaxCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
